(setq evil-default-state 'emacs)


(require 'evil-surround)
(require 'evil)

(define-key global-map (kbd "C-z") nil)
(define-key global-map (kbd "H-h") 'windmove-left)
(define-key global-map (kbd "H-j") 'windmove-down)
(define-key global-map (kbd "H-k") 'windmove-up)
(define-key global-map (kbd "H-l") 'windmove-right)
(define-key global-map (kbd "H-H") 'evil-window-move-far-left)
(define-key global-map (kbd "H-J") 'evil-window-move-very-bottom)
(define-key global-map (kbd "H-K") 'evil-window-move-very-top)
(define-key global-map (kbd "H-L") 'evil-window-move-far-right)
(define-key global-map (kbd "H-o") 'other-window)
(define-key global-map (kbd "H-0") 'delete-window)
(define-key global-map (kbd "H-1") 'delete-other-windows)
(define-key global-map (kbd "H-2") 'split-window-below)
(define-key global-map (kbd "H-3") 'split-window-right)
(define-key global-map (kbd "C-c o i") 'deh/open-init-file)
(define-key global-map (kbd "C-c o n") 'deh/open-notes-file)
(define-key global-map (kbd "C-c o s") 'deh/open-scratch-buffer)
(define-key global-map (kbd "M-i") 'helm-imenu)
(define-key global-map (kbd "M-I") 'helm-imenu-in-all-buffers)

(evil-surround-mode)

(evil-mode 1)
(evil-set-initial-state 'php-mode 'normal)
(evil-set-initial-state 'web-mode 'normal)
(evil-set-initial-state 'visual-basic-mode 'normal)
(evil-set-initial-state 'json-mode 'normal)
(evil-set-initial-state 'js2-mode 'normal)
(evil-set-initial-state 'kotlin-mode 'normal)
(evil-set-initial-state 'java-mode 'normal)
(evil-set-initial-state 'fsharp-mode 'normal)
(evil-set-initial-state 'go-mode 'normal)
(evil-set-initial-state 'eshell-mode 'emacs)
(evil-set-initial-state 'shell-mode 'emacs)
(evil-set-initial-state 'help-mode 'emacs)

(defvar deh/evil-leader-map (make-sparse-keymap)
  "Keymap for \"leader key\" shortcuts.")
(define-key evil-normal-state-map (kbd "SPC") deh/evil-leader-map)
(define-key deh/evil-leader-map ";" 'ace-jump-char-mode)

(define-key evil-normal-state-map (kbd "M-w") 'save-buffer)
(define-key evil-insert-state-map (kbd "M-w") 'save-buffer)
(define-key evil-normal-state-map (kbd "M-c") 'delete-window)
(define-key evil-normal-state-map (kbd "M-o") 'delete-other-windows)
(define-key evil-normal-state-map (kbd "M-q") '(lambda ()
						 (interactive)
						 (evil-delete-buffer (current-buffer))))

(provide 'deh-evil)
