tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'
tap 'neovim/neovim'

brew 'ack'
brew 'ag'
brew 'composer'
brew 'coreutils'
brew 'ctags'
brew 'fontconfig'
brew 'htop'
brew 'mysql'
brew 'neovim'
brew 'php71'
brew 'php71-mcrypt'
brew 'php71-xdebug'
brew 'pwgen'
brew 'python'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'stow'
brew 'tmux'
brew 'wget'
brew 'zsh'


cask 'iterm2'
cask 'sequel-pro'
