sudo apt update
sudo apt install -y \
     ack \
     composer \
		 docker-ce \
     emacs \
     emacs25-common-non-dfsg \
     exuberant-ctags \
     graphviz \
     konsole \
     mpd \
     mycli \
     mysql-server \
     ncmpcpp \
     neovim \
     openjdk-8-jdk \
     php7.0 \
     php7.0-cli \
     php7.0-curl \
     php7.0-fpm \
     php7.0-mbstring \
     php7.0-mcrypt \
     php7.0-mysql \
     php7.0-pgsql \
     php7.0-sqlite3 \
     php7.0-xml \
     php7.0-zip \
     pwgen \
     python \
     python3 \
     python3-pip \
     python-pip \
     rsync \
     rxvt-unicode-256color \
     silversearcher-ag \
     sqlite \
     stow \
     tmux \
     yarn \
     zsh
